[package]
name = "settings-example"
version.workspace = true
edition.workspace = true

[dependencies]
rip-settings = { path = "../settings-core" }
rip-settings-derive = { path = "../settings-derive" }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
